global:
  resolve_timeout: 1m

inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info|attention  # 新しい優先度 'attention' を追加
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity =~ info|attention
  - equal:
      - namespace
    source_matchers:
      - alertname = InfoInhibitor
    target_matchers:
      - severity = info
  - target_matchers:
      - alertname = InfoInhibitor

receivers:
  - name: 'webhook-trouble-handler'
    webhook_configs:
      - url: 'http://<アラートを受け取るノードのホスト名またはIPアドレス>:9083'
        send_resolved: true
  
route:
  group_by:
    - severity
  group_interval: 10m
  group_wait: 1m
  repeat_interval: 5m
  receiver: webhook-trouble-handler

templates:
  - /etc/alertmanager/config/*.tmpl
